### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by OneScheer** [rempopo/CO24_Sowing_path.zargabad#1]
1.  Briefing: строчка 57 `т.к. в районе опасно размещать обслуживающие пункты, вам будет доступен CCP и FARP на US Airfiel.` опечатка.
2.  В целом расположение FARP и CCP выглядит странным.  Единственная дорога до аэродрома проходит через Extraction. То есть уничтожив противника в лагере и решив залечиться/поремонтироваться, игроки заедут в BaseTrg и миссия закончится. Такая же ситуация с условием по уничтожению только мин.  Предлагаю FARP/CCP поставить рядом с точкой появления игроков.

**Comment by Comrade333** [comment]
Готово.

**Comment by 10Dozen** [comment]
У вас в Ридми название кривое - трабло де мерда

**Comment by OneScheer** [comment]
Опечатка так и не исправлена, но это не критично. В принципе апрувлю
